# Generated by Django 4.0.1 on 2022-03-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_user_email_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=200),
        ),
    ]
